/**
 * @file PoleMixingCorrections_generated.h
 * @brief Cutoff and resonance corrections for Filter1Pole4StageSmooth, regenerated from
 * direct measurement of the raw (uncorrected) filter.
 *
 * Generated by documentation/Filters/PoleMixing/fitPoleMixingCorrections.py from
 * documentation/Filters/PoleMixing/pm_raw_correction_data.txt - see that folder's
 * README.md. Do not hand-edit: regenerate via fitPoleMixingCorrections.py instead.
 */
#pragma once

#include <algorithm>
#include <cmath>

namespace AbacDsp
{

/**
 * correctedRawCutoffForTargetFrequency(targetHz) returns the raw cutoff to feed
 * setCutoffFrequencyClean() so the filter's actual resonant peak lands at targetHz, at 90%
 * of critical resonance. Fit domain: [20.0, 8564.1] Hz. Degree 7
 * polynomial in log(targetHz) -> log(rawCutoff). Max relative error over the fit domain:
 * 1.550%, mean 0.523%.
 */
[[nodiscard]] inline float correctedRawCutoffForTargetFrequency(const float targetHz) noexcept
{
    // fit domain: [20.0, 8564.1] Hz - clamp the input so an out-of-domain request
    // extrapolates the polynomial from its own edge rather than from an arbitrary far-off point.
    const float clampedHz = std::clamp(targetHz, 20.0f, 8564.1f);
    const float logTarget = std::log(clampedHz);
    return std::clamp(std::exp((((((((9.6349029396e-05f * logTarget + -3.8678729667e-03f) * logTarget + 6.5635779915e-02f) * logTarget + -6.0948291407e-01f) * logTarget + 3.3407285201e+00f) * logTarget + -1.0797447481e+01f) * logTarget + 2.0035427289e+01f) * logTarget + -1.4090183062e+01f)), 10.f, 22000.f);
}

/**
 * criticalResonanceForRawCutoff(rawCutoffHz) returns the measured self-oscillation-threshold
 * resonance at the given raw cutoff. Filter1Pole4StageSmooth::setResonance() multiplies its
 * normalized (0=none, 1=at threshold) input by this, so a given resonance value means
 * roughly the same thing at any cutoff. Fit domain: [20.0, 19706.4] Hz. Degree
 * 7 polynomial in log(rawCutoffHz) -> log(criticalResonance). Max relative error over
 * the fit domain: 0.903%, mean 0.252%.
 */
[[nodiscard]] inline float criticalResonanceForRawCutoff(const float rawCutoffHz) noexcept
{
    const float clampedHz = std::clamp(rawCutoffHz, 20.0f, 19706.4f);
    const float logCutoff = std::log(clampedHz);
    return std::exp((((((((1.5652016830e-04f * logCutoff + -6.3862819811e-03f) * logCutoff + 1.1006970626e-01f) * logCutoff + -1.0354941443e+00f) * logCutoff + 5.7326806873e+00f) * logCutoff + -1.8653801684e+01f) * logCutoff + 3.3017260953e+01f) * logCutoff + -2.3147311425e+01f));
}

}
