/**
 * @file PoleMixingCorrections_generated.h
 * @brief Cutoff correction for Filter1Pole4StageSmooth, regenerated from direct measurement.
 *
 * Generated by documentation/Filters/PoleMixing/fitCutoffCorrection.py from
 * documentation/Filters/PoleMixing/pm_raw_correction_data.txt (raw, uncorrected sweep of
 * Filter1Pole4StageSmooth's bandpass-tap topology - see that folder's README.md). Do not
 * hand-edit: regenerate via fitCutoffCorrection.py instead.
 *
 * correctedRawCutoffForTargetFrequency(targetHz) returns the raw cutoff to feed
 * setCutoffFrequencyClean() so the filter's actual resonant peak lands at targetHz, at 90%
 * of critical resonance. Fit domain: [20.0, 8564.1] Hz. Degree 7
 * polynomial in log(targetHz) -> log(rawCutoff). Max relative error over the fit domain:
 * 1.550%, mean 0.523%.
 *
 * Critical (self-oscillation-threshold) resonance over the same sweep ranged
 * [3.9348, 19.9718] around a mean of 5.5001
 * (291.6% relative spread) - see the folder README for whether
 * that spread is judged small enough to leave uncorrected.
 */
#pragma once

#include <algorithm>
#include <cmath>

namespace AbacDsp
{

[[nodiscard]] inline float correctedRawCutoffForTargetFrequency(const float targetHz) noexcept
{
    // fit domain: [20.0, 8564.1] Hz - clamp the input so an out-of-domain request
    // extrapolates the polynomial from its own edge rather than from an arbitrary far-off point.
    const float clampedHz = std::clamp(targetHz, 20.0f, 8564.1f);
    const float logTarget = std::log(clampedHz);
    return std::clamp(std::exp((((((((9.6349029396e-05f * logTarget + -3.8678729667e-03f) * logTarget + 6.5635779915e-02f) * logTarget + -6.0948291407e-01f) * logTarget + 3.3407285201e+00f) * logTarget + -1.0797447481e+01f) * logTarget + 2.0035427289e+01f) * logTarget + -1.4090183062e+01f)), 10.f, 22000.f);
}

}
