// Generated by dev-scripts/generate_graph_presets.py from Graph/Presets/lua/*.lua.
// Do not edit: change the .lua files and run dev-scripts/dev-generate-presets.sh.
#pragma once

#include <array>
#include <string_view>

namespace AbacDsp::Graph::Presets
{

struct Preset
{
    std::string_view name;
    std::string_view lua;
};

// clang-format off
inline constexpr std::string_view kTapeVibrato = R"lua(-- Family 1: tape vibrato. One stereo TapeDelay, 100% wet, shared wow and flutter.
-- Ports mirror pathfinder. Macros are declarative: a host applies them by hand.
return {
  version = 1,
  name = "Tape Vibrato",

  io = { inputs = { "inL", "inR" }, outputs = { "outL", "outR" } },

  nodes = {
    { id = "tape", type = "TapeDelay",
      config = { baseDelayMs = 8 },
      params = {
        transportRatio = 1.0,
        wowDepth = 0.60, wowRate = 0.50, wowVariance = 0.10, wowDrift = 0.00,
        flutterDepth = 0.65, flutterRate = 5.0,
      },
    },
  },

  edges = {
    { from = "inL", to = "tape.inL" },
    { from = "inR", to = "tape.inR" },
    { from = "tape.outL", to = "outL" },
    { from = "tape.outR", to = "outR" },
  },

  macros = {
    { id = "depth", label = "Depth", default = 0.35,
      targets = { { to = "tape.wowDepth", map = "vibratoWowDepth" },
                  { to = "tape.flutterDepth", map = "vibratoFlutterDepth" } } },
    { id = "speed", label = "Speed", default = 0.35,
      targets = { { to = "tape.wowRate", map = "vibratoWowRate" },
                  { to = "tape.flutterRate", map = "vibratoFlutterRate" } } },
    { id = "aggressivity", label = "OU Aggressivity", default = 0.15,
      targets = { { to = "tape.wowVariance", map = "vibratoWowVariance" },
                  { to = "tape.wowDrift", map = "vibratoWowDrift" } } },
    { id = "character", label = "Character", default = 0.50,
      targets = { { to = "tape.transportRatio", map = "tapeToCleanTransportRatio" } } },
  },
}
)lua";

inline constexpr std::string_view kClassicStereoChorus = R"lua(-- Family 2: classic stereo chorus, dual mono.
-- One TapeDelay per channel with its own seed, so left and right wobble independently.
-- Each TapeDelay is stereo: only its own channel is fed and read.
return {
  version = 1,
  name = "Classic Stereo Chorus",

  io = { inputs = { "inL", "inR" }, outputs = { "outL", "outR" } },

  nodes = {
    { id = "tapeL", type = "TapeDelay", config = { baseDelayMs = 12, seed = 11 },
      params = { wowDepth = 0.50, wowRate = 0.40, wowVariance = 0.10, flutterDepth = 0.42, flutterRate = 0.80 } },
    { id = "tapeR", type = "TapeDelay", config = { baseDelayMs = 12, seed = 23 },
      params = { wowDepth = 0.50, wowRate = 0.47, wowVariance = 0.10, flutterDepth = 0.50, flutterRate = 0.95 } },

    { id = "toneL", type = "TiltEQ", params = { tiltDb = -2.0, pivotHz = 1000 } },
    { id = "toneR", type = "TiltEQ", params = { tiltDb = -2.0, pivotHz = 1000 } },
    { id = "wet", type = "Gain", params = { gainDb = -3.0 } },
    { id = "dry", type = "Gain", params = { gainDb = 0.0 } },
    { id = "mix", type = "Mixer" },
  },

  edges = {
    { from = "inL", to = "tapeL.inL" },
    { from = "inR", to = "tapeR.inR" },
    { from = "tapeL.outL", to = "toneL.in" },
    { from = "tapeR.outR", to = "toneR.in" },
    { from = "toneL.out", to = "wet.inL" },
    { from = "toneR.out", to = "wet.inR" },
    { from = "wet.outL", to = "mix.in1L" },
    { from = "wet.outR", to = "mix.in1R" },
    { from = "inL", to = "dry.inL" },
    { from = "inR", to = "dry.inR" },
    { from = "dry.outL", to = "mix.in2L" },
    { from = "dry.outR", to = "mix.in2R" },
    { from = "mix.outL", to = "outL" },
    { from = "mix.outR", to = "outR" },
  },
}
)lua";

inline constexpr std::string_view kSharedTransportHeads = R"lua(-- Family 3: shared-transport tape-head chorus.
-- Two TapeDelay with the same seed and wow/flutter move in lockstep, like two heads on one
-- transport, at different base delays. A Matrix per head leans it left or right.
-- Approximation: no per-head drift; a real multi-head delay would be a new node.
return {
  version = 1,
  name = "Shared Transport Heads",

  io = { inputs = { "inL", "inR" }, outputs = { "outL", "outR" } },

  nodes = {
    { id = "headA", type = "TapeDelay", config = { baseDelayMs = 10, seed = 5 },
      params = { wowDepth = 0.50, wowRate = 0.35, wowVariance = 0.10, flutterDepth = 0.42, flutterRate = 0.70 } },
    { id = "headB", type = "TapeDelay", config = { baseDelayMs = 15, seed = 5 },
      params = { wowDepth = 0.50, wowRate = 0.35, wowVariance = 0.10, flutterDepth = 0.42, flutterRate = 0.70 } },

    { id = "gainA", type = "Gain", params = { gainDb = -6.0 } },
    { id = "gainB", type = "Gain", params = { gainDb = -7.5 } },
    { id = "leanA", type = "Matrix", params = { gainLL = 1.0, gainLR = 0.35, gainRL = 0.0, gainRR = 0.65 } },
    { id = "leanB", type = "Matrix", params = { gainLL = 0.65, gainLR = 0.0, gainRL = 0.35, gainRR = 1.0 } },
    { id = "heads", type = "Mixer" },

    { id = "toneL", type = "TiltEQ", params = { tiltDb = -2.5, pivotHz = 1000 } },
    { id = "toneR", type = "TiltEQ", params = { tiltDb = -2.5, pivotHz = 1000 } },
    { id = "wet", type = "Gain", params = { gainDb = -2.0 } },
    { id = "dry", type = "Gain", params = { gainDb = 0.0 } },
    { id = "mix", type = "Mixer" },
  },

  edges = {
    { from = "inL", to = "headA.inL" },
    { from = "inR", to = "headA.inR" },
    { from = "inL", to = "headB.inL" },
    { from = "inR", to = "headB.inR" },
    { from = "headA.outL", to = "gainA.inL" },
    { from = "headA.outR", to = "gainA.inR" },
    { from = "headB.outL", to = "gainB.inL" },
    { from = "headB.outR", to = "gainB.inR" },
    { from = "gainA.outL", to = "leanA.inL" },
    { from = "gainA.outR", to = "leanA.inR" },
    { from = "gainB.outL", to = "leanB.inL" },
    { from = "gainB.outR", to = "leanB.inR" },
    { from = "leanA.outL", to = "heads.in1L" },
    { from = "leanA.outR", to = "heads.in1R" },
    { from = "leanB.outL", to = "heads.in2L" },
    { from = "leanB.outR", to = "heads.in2R" },
    { from = "heads.outL", to = "toneL.in" },
    { from = "heads.outR", to = "toneR.in" },
    { from = "toneL.out", to = "wet.inL" },
    { from = "toneR.out", to = "wet.inR" },
    { from = "wet.outL", to = "mix.in1L" },
    { from = "wet.outR", to = "mix.in1R" },
    { from = "inL", to = "dry.inL" },
    { from = "inR", to = "dry.inR" },
    { from = "dry.outL", to = "mix.in2L" },
    { from = "dry.outR", to = "mix.in2R" },
    { from = "mix.outL", to = "outL" },
    { from = "mix.outR", to = "outR" },
  },
}
)lua";

inline constexpr std::string_view kEnsembleTriChorus = R"lua(-- Family 4: multi-voice ensemble (tri-chorus).
-- Three TapeDelay voices with their own seed, rate, base delay and drift, so their
-- modulation is independent. Each voice runs at 1/sqrt(3), -4.77 dB, so three voices sum to
-- the level of one. Matrices lean the voices left, centre and right.
return {
  version = 1,
  name = "Ensemble Tri-Chorus",

  io = { inputs = { "inL", "inR" }, outputs = { "outL", "outR" } },

  nodes = {
    { id = "voice1", type = "TapeDelay", config = { baseDelayMs = 11, seed = 101 },
      params = { wowDepth = 0.50, wowRate = 0.30, wowVariance = 0.20, wowDrift = 0.20, flutterDepth = 0.40, flutterRate = 0.60 } },
    { id = "voice2", type = "TapeDelay", config = { baseDelayMs = 15, seed = 202 },
      params = { wowDepth = 0.50, wowRate = 0.40, wowVariance = 0.20, wowDrift = 0.20, flutterDepth = 0.48, flutterRate = 0.80 } },
    { id = "voice3", type = "TapeDelay", config = { baseDelayMs = 20, seed = 303 },
      params = { wowDepth = 0.50, wowRate = 0.50, wowVariance = 0.20, wowDrift = 0.20, flutterDepth = 0.58, flutterRate = 1.05 } },

    { id = "gain1", type = "Gain", params = { gainDb = -4.77 } },
    { id = "gain2", type = "Gain", params = { gainDb = -4.77 } },
    { id = "gain3", type = "Gain", params = { gainDb = -4.77 } },
    { id = "lean1", type = "Matrix", params = { gainLL = 1.0, gainLR = 0.4, gainRL = 0.0, gainRR = 0.6 } },
    { id = "lean2", type = "Matrix", params = { gainLL = 0.8, gainLR = 0.2, gainRL = 0.2, gainRR = 0.8 } },
    { id = "lean3", type = "Matrix", params = { gainLL = 0.6, gainLR = 0.0, gainRL = 0.4, gainRR = 1.0 } },
    { id = "sum12", type = "Mixer" },
    { id = "sum123", type = "Mixer" },

    { id = "toneL", type = "TiltEQ", params = { tiltDb = -2.0, pivotHz = 1000 } },
    { id = "toneR", type = "TiltEQ", params = { tiltDb = -2.0, pivotHz = 1000 } },
    { id = "wet", type = "Gain", params = { gainDb = -2.0 } },
    { id = "dry", type = "Gain", params = { gainDb = 0.0 } },
    { id = "mix", type = "Mixer" },
  },

  edges = {
    { from = "inL", to = "voice1.inL" },
    { from = "inR", to = "voice1.inR" },
    { from = "inL", to = "voice2.inL" },
    { from = "inR", to = "voice2.inR" },
    { from = "inL", to = "voice3.inL" },
    { from = "inR", to = "voice3.inR" },

    { from = "voice1.outL", to = "gain1.inL" },
    { from = "voice1.outR", to = "gain1.inR" },
    { from = "voice2.outL", to = "gain2.inL" },
    { from = "voice2.outR", to = "gain2.inR" },
    { from = "voice3.outL", to = "gain3.inL" },
    { from = "voice3.outR", to = "gain3.inR" },

    { from = "gain1.outL", to = "lean1.inL" },
    { from = "gain1.outR", to = "lean1.inR" },
    { from = "gain2.outL", to = "lean2.inL" },
    { from = "gain2.outR", to = "lean2.inR" },
    { from = "gain3.outL", to = "lean3.inL" },
    { from = "gain3.outR", to = "lean3.inR" },

    { from = "lean1.outL", to = "sum12.in1L" },
    { from = "lean1.outR", to = "sum12.in1R" },
    { from = "lean2.outL", to = "sum12.in2L" },
    { from = "lean2.outR", to = "sum12.in2R" },
    { from = "sum12.outL", to = "sum123.in1L" },
    { from = "sum12.outR", to = "sum123.in1R" },
    { from = "lean3.outL", to = "sum123.in2L" },
    { from = "lean3.outR", to = "sum123.in2R" },

    { from = "sum123.outL", to = "toneL.in" },
    { from = "sum123.outR", to = "toneR.in" },
    { from = "toneL.out", to = "wet.inL" },
    { from = "toneR.out", to = "wet.inR" },
    { from = "wet.outL", to = "mix.in1L" },
    { from = "wet.outR", to = "mix.in1R" },
    { from = "inL", to = "dry.inL" },
    { from = "inR", to = "dry.inR" },
    { from = "dry.outL", to = "mix.in2L" },
    { from = "dry.outR", to = "mix.in2R" },
    { from = "mix.outL", to = "outL" },
    { from = "mix.outR", to = "outR" },
  },
}
)lua";

inline constexpr std::string_view kCrossoverPreserveStereo = R"lua(-- Crossover-safe chorus, policy 1: preserve the stereo low band.
-- The low band bypasses the delay and stays dry; the high band is processed.
return {
  version = 1,
  name = "Preserve Stereo Low Band",
  io = { inputs = { "inL", "inR" }, outputs = { "outL", "outR" } },
  nodes = {
    { id = "xoL", type = "CrossoverLR4", params = { frequencyHz = 200 } },
    { id = "xoR", type = "CrossoverLR4", params = { frequencyHz = 200 } },
    { id = "tape", type = "TapeDelay" },
    { id = "mix", type = "Mixer" },
  },
  edges = {
    { from = "inL", to = "xoL.in" },
    { from = "inR", to = "xoR.in" },
    { from = "xoL.highOut", to = "tape.inL" },
    { from = "xoR.highOut", to = "tape.inR" },
    { from = "tape.outL", to = "mix.in1L" },
    { from = "tape.outR", to = "mix.in1R" },
    { from = "xoL.lowOut", to = "mix.in2L" },
    { from = "xoR.lowOut", to = "mix.in2R" },
    { from = "mix.outL", to = "outL" },
    { from = "mix.outR", to = "outR" },
  },
}
)lua";

inline constexpr std::string_view kCrossoverMonoLow = R"lua(-- Crossover-safe chorus, policy 2: mono low band.
-- Same split; the low band is folded to mono before it is recombined.
return {
  version = 1,
  name = "Mono Low Band",
  io = { inputs = { "inL", "inR" }, outputs = { "outL", "outR" } },
  nodes = {
    { id = "xoL", type = "CrossoverLR4", params = { frequencyHz = 200 } },
    { id = "xoR", type = "CrossoverLR4", params = { frequencyHz = 200 } },
    { id = "lowMono", type = "StereoToMono" },
    { id = "lowDup", type = "MonoToStereo" },
    { id = "tape", type = "TapeDelay" },
    { id = "mix", type = "Mixer" },
  },
  edges = {
    { from = "inL", to = "xoL.in" },
    { from = "inR", to = "xoR.in" },
    { from = "xoL.lowOut", to = "lowMono.inL" },
    { from = "xoR.lowOut", to = "lowMono.inR" },
    { from = "lowMono.out", to = "lowDup.in" },
    { from = "xoL.highOut", to = "tape.inL" },
    { from = "xoR.highOut", to = "tape.inR" },
    { from = "tape.outL", to = "mix.in1L" },
    { from = "tape.outR", to = "mix.in1R" },
    { from = "lowDup.outL", to = "mix.in2L" },
    { from = "lowDup.outR", to = "mix.in2R" },
    { from = "mix.outL", to = "outL" },
    { from = "mix.outR", to = "outR" },
  },
}
)lua";

inline constexpr std::string_view kCrossoverWetOnlyLowCut = R"lua(-- Crossover-safe chorus, policy 3: wet-only low cut.
-- No split; the full dry signal stays and only the wet bus is high-passed.
return {
  version = 1,
  name = "Wet Only Low Cut",
  io = { inputs = { "inL", "inR" }, outputs = { "outL", "outR" } },
  nodes = {
    { id = "tape", type = "TapeDelay" },
    { id = "wetHpL", type = "OnePoleHP", params = { cutoffHz = 200 } },
    { id = "wetHpR", type = "OnePoleHP", params = { cutoffHz = 200 } },
    { id = "mix", type = "Mixer" },
  },
  edges = {
    { from = "inL", to = "tape.inL" },
    { from = "inR", to = "tape.inR" },
    { from = "tape.outL", to = "wetHpL.in" },
    { from = "tape.outR", to = "wetHpR.in" },
    { from = "wetHpL.out", to = "mix.in1L" },
    { from = "wetHpR.out", to = "mix.in1R" },
    { from = "inL", to = "mix.in2L" },
    { from = "inR", to = "mix.in2R" },
    { from = "mix.outL", to = "outL" },
    { from = "mix.outR", to = "outR" },
  },
}
)lua";

inline constexpr std::array<Preset, 7> kChorusPresets{{
    {"tape_vibrato", kTapeVibrato},
    {"classic_stereo_chorus", kClassicStereoChorus},
    {"shared_transport_heads", kSharedTransportHeads},
    {"ensemble_tri_chorus", kEnsembleTriChorus},
    {"crossover_preserve_stereo", kCrossoverPreserveStereo},
    {"crossover_mono_low", kCrossoverMonoLow},
    {"crossover_wet_only_low_cut", kCrossoverWetOnlyLowCut},
}};
// clang-format on

}
