#!/usr/bin/env python3

# Fits a correction from raw (uncorrected) pole-mixing filter measurements, following the
# same measure -> curve_fit -> emit-C++ pattern as
# documentation/Filters/BandpassImpulses/fitBandPassCompensation.py. Reads
# pm_raw_correction_data.txt (raw_cutoff_hz measured_peak_hz critical_resonance, one row per
# swept raw cutoff) and fits target peak frequency -> required raw cutoff, comparing a plain
# cubic in linear Hz (the old adaptResonanceFrequency()'s model shape) against a polynomial
# fit in log-frequency space, then emits the better one as a generated C++ header. Also
# reports how much critical resonance drifts with cutoff, to decide whether it needs its own
# correction (Phase 2, not generated here).

import argparse
import numpy as np


def load_data(path):
    raw_cutoff, measured_peak, critical_resonance = np.loadtxt(path, comments="#", unpack=True)
    return raw_cutoff, measured_peak, critical_resonance


def trim_to_musical_resonance_range(raw_cutoff, measured_peak, critical_resonance, max_resonance):
    # A plain least-squares polyfit doesn't need monotonic or noise-free y data - occasional
    # duplicate/out-of-order measured_peak values (the peak search's 1.02x grid is coarser
    # than the sweep's own ~1.0194x step, so adjacent points sometimes tie or jitter) are not
    # a problem for it. What *is* a problem is relevance: above some critical resonance no
    # musical use case sets resonance that high, and the measurement itself gets less precise
    # there too (very broad, shallow peaks). Keep only points at or below max_resonance.
    keep = critical_resonance <= max_resonance
    return raw_cutoff[keep], measured_peak[keep], critical_resonance[keep]


def fit_linear_cubic(target, raw_cutoff):
    coeffs = np.polyfit(target, raw_cutoff, 3)
    predicted = np.polyval(coeffs, target)
    return coeffs, predicted


def fit_log_polynomial(target, raw_cutoff, degree):
    log_target = np.log(target)
    log_raw = np.log(raw_cutoff)
    coeffs = np.polyfit(log_target, log_raw, degree)
    predicted = np.exp(np.polyval(coeffs, log_target))
    return coeffs, predicted


def relative_error_stats(measured, predicted):
    rel_err = np.abs(predicted - measured) / measured
    return float(np.max(rel_err)), float(np.mean(rel_err))


def format_horner_natural(coeffs, var_name):
    terms = [f"{c:.10e}f" for c in coeffs]
    expr = terms[0]
    for c in terms[1:]:
        expr = f"({expr} * {var_name} + {c})"
    return expr


def emit_header(degree, coeffs, max_err, mean_err, lo_hz, hi_hz, resonance_lo, resonance_hi,
                resonance_mean, resonance_rel_spread):
    horner = format_horner_natural(list(coeffs), "logTarget")
    doxygen = f"""/**
 * @file PoleMixingCorrections_generated.h
 * @brief Cutoff correction for Filter1Pole4StageSmooth, regenerated from direct measurement.
 *
 * Generated by documentation/Filters/PoleMixing/fitCutoffCorrection.py from
 * documentation/Filters/PoleMixing/pm_raw_correction_data.txt (raw, uncorrected sweep of
 * Filter1Pole4StageSmooth's bandpass-tap topology - see that folder's README.md). Do not
 * hand-edit: regenerate via fitCutoffCorrection.py instead.
 *
 * correctedRawCutoffForTargetFrequency(targetHz) returns the raw cutoff to feed
 * setCutoffFrequencyClean() so the filter's actual resonant peak lands at targetHz, at 90%
 * of critical resonance. Fit domain: [{lo_hz:.1f}, {hi_hz:.1f}] Hz. Degree {degree}
 * polynomial in log(targetHz) -> log(rawCutoff). Max relative error over the fit domain:
 * {max_err * 100.0:.3f}%, mean {mean_err * 100.0:.3f}%.
 *
 * Critical (self-oscillation-threshold) resonance over the same sweep ranged
 * [{resonance_lo:.4f}, {resonance_hi:.4f}] around a mean of {resonance_mean:.4f}
 * ({resonance_rel_spread * 100.0:.1f}% relative spread) - see the folder README for whether
 * that spread is judged small enough to leave uncorrected.
 */
"""
    return (
        doxygen
        + "#pragma once\n\n#include <algorithm>\n#include <cmath>\n\nnamespace AbacDsp\n{\n\n"
        + "[[nodiscard]] inline float correctedRawCutoffForTargetFrequency(const float targetHz) noexcept\n{\n"
        + f"    // fit domain: [{lo_hz:.1f}, {hi_hz:.1f}] Hz - clamp the input so an out-of-domain request\n"
        + "    // extrapolates the polynomial from its own edge rather than from an arbitrary far-off point.\n"
        + f"    const float clampedHz = std::clamp(targetHz, {lo_hz:.1f}f, {hi_hz:.1f}f);\n"
        + "    const float logTarget = std::log(clampedHz);\n"
        + f"    return std::clamp(std::exp({horner}), 10.f, 22000.f);\n"
        + "}\n\n}\n"
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-f", "--infile", default="pm_raw_correction_data.txt")
    parser.add_argument("-o", "--outfile", default="PoleMixingCorrections_generated.h")
    parser.add_argument("--degree", type=int, default=5, help="log-space polynomial degree to emit")
    parser.add_argument("--max-resonance", type=float, default=20.0,
                        help="drop points whose measured critical resonance exceeds this (not musically useful)")
    args = parser.parse_args()

    raw_cutoff_full, measured_peak_full, critical_resonance_full = load_data(args.infile)
    print(f"Loaded {len(raw_cutoff_full)} points from {args.infile}")

    raw_cutoff, measured_peak, critical_resonance = trim_to_musical_resonance_range(
        raw_cutoff_full, measured_peak_full, critical_resonance_full, args.max_resonance)
    print(f"Kept {len(raw_cutoff)} of {len(raw_cutoff_full)} points "
          f"(critical_resonance <= {args.max_resonance})")
    print(f"raw_cutoff range: {raw_cutoff.min():.1f} - {raw_cutoff.max():.1f} Hz")
    print(f"measured_peak range: {measured_peak.min():.1f} - {measured_peak.max():.1f} Hz")

    # Old model shape: a plain cubic in linear Hz (matches adaptResonanceFrequency()'s low
    # branch), fit here to the *raw* data for a fair, apples-to-apples error comparison.
    _, predicted_linear = fit_linear_cubic(measured_peak, raw_cutoff)
    max_err_linear, mean_err_linear = relative_error_stats(raw_cutoff, predicted_linear)
    print(f"\nLinear-Hz cubic fit (old model shape): max err {max_err_linear * 100:.2f}%, "
          f"mean err {mean_err_linear * 100:.2f}%")

    print("\nLog-space polynomial fit, by degree:")
    best_degree = None
    best_coeffs = None
    best_predicted = None
    best_max_err = None
    best_mean_err = None
    for degree in range(3, 8):
        coeffs, predicted = fit_log_polynomial(measured_peak, raw_cutoff, degree)
        max_err, mean_err = relative_error_stats(raw_cutoff, predicted)
        print(f"  degree {degree}: max err {max_err * 100:.3f}%, mean err {mean_err * 100:.3f}%")
        if degree == args.degree:
            best_degree, best_coeffs, best_predicted = degree, coeffs, predicted
            best_max_err, best_mean_err = max_err, mean_err

    if best_coeffs is None:
        raise SystemExit(f"--degree {args.degree} was not evaluated (must be 3..7)")

    resonance_lo = float(critical_resonance.min())
    resonance_hi = float(critical_resonance.max())
    resonance_mean = float(critical_resonance.mean())
    resonance_rel_spread = (resonance_hi - resonance_lo) / resonance_mean
    print(f"\ncritical_resonance range: {resonance_lo:.4f} - {resonance_hi:.4f} "
          f"(mean {resonance_mean:.4f}, {resonance_rel_spread * 100:.1f}% relative spread)")

    header = emit_header(best_degree, best_coeffs, best_max_err, best_mean_err,
                         float(measured_peak.min()), float(measured_peak.max()),
                         resonance_lo, resonance_hi, resonance_mean, resonance_rel_spread)
    with open(args.outfile, "w") as f:
        f.write(header)
    print(f"\nWrote {args.outfile} (degree {best_degree}, "
          f"max err {best_max_err * 100:.3f}%, mean err {best_mean_err * 100:.3f}%)")


if __name__ == "__main__":
    main()
