-- Family 3: shared-transport tape-head chorus.
-- Two TapeDelay with the same seed and wow/flutter move in lockstep, like two heads on one
-- transport, at different base delays. A Matrix per head leans it left or right.
-- Approximation: no per-head drift; a real multi-head delay would be a new node.
-- Each macro is one knob; its default is in the knob's own units and reproduces the values below.
return {
  version = 1,
  name = "Shared Transport Heads",

  io = { inputs = { "inL", "inR" }, outputs = { "outL", "outR" } },

  nodes = {
    { id = "headA", type = "TapeDelay", config = { baseDelayMs = 10, seed = 5 },
      params = { wowDepth = 0.50, wowRate = 0.35, wowVariance = 0.10, flutterDepth = 0.42, flutterRate = 0.70 } },
    { id = "headB", type = "TapeDelay", config = { baseDelayMs = 15, seed = 5 },
      params = { wowDepth = 0.50, wowRate = 0.35, wowVariance = 0.10, flutterDepth = 0.42, flutterRate = 0.70 } },

    { id = "gainA", type = "Gain", params = { gainDb = -6.0 } },
    { id = "gainB", type = "Gain", params = { gainDb = -7.5 } },
    { id = "leanA", type = "Matrix", params = { gainLL = 1.0, gainLR = 0.35, gainRL = 0.0, gainRR = 0.65 } },
    { id = "leanB", type = "Matrix", params = { gainLL = 0.65, gainLR = 0.0, gainRL = 0.35, gainRR = 1.0 } },
    { id = "heads", type = "Mixer" },

    { id = "toneL", type = "TiltEQ", params = { tiltDb = -2.5, pivotHz = 1000 } },
    { id = "toneR", type = "TiltEQ", params = { tiltDb = -2.5, pivotHz = 1000 } },
    { id = "wet", type = "Gain", params = { gainDb = -2.0 } },
    { id = "dry", type = "Gain", params = { gainDb = 0.0 } },
    { id = "mix", type = "Mixer" },
  },

  edges = {
    { from = "inL", to = "headA.inL" },
    { from = "inR", to = "headA.inR" },
    { from = "inL", to = "headB.inL" },
    { from = "inR", to = "headB.inR" },
    { from = "headA.outL", to = "gainA.inL" },
    { from = "headA.outR", to = "gainA.inR" },
    { from = "headB.outL", to = "gainB.inL" },
    { from = "headB.outR", to = "gainB.inR" },
    { from = "gainA.outL", to = "leanA.inL" },
    { from = "gainA.outR", to = "leanA.inR" },
    { from = "gainB.outL", to = "leanB.inL" },
    { from = "gainB.outR", to = "leanB.inR" },
    { from = "leanA.outL", to = "heads.in1L" },
    { from = "leanA.outR", to = "heads.in1R" },
    { from = "leanB.outL", to = "heads.in2L" },
    { from = "leanB.outR", to = "heads.in2R" },
    { from = "heads.outL", to = "toneL.in" },
    { from = "heads.outR", to = "toneR.in" },
    { from = "toneL.out", to = "wet.inL" },
    { from = "toneR.out", to = "wet.inR" },
    { from = "wet.outL", to = "mix.in1L" },
    { from = "wet.outR", to = "mix.in1R" },
    { from = "inL", to = "dry.inL" },
    { from = "inR", to = "dry.inR" },
    { from = "dry.outL", to = "mix.in2L" },
    { from = "dry.outR", to = "mix.in2R" },
    { from = "mix.outL", to = "outL" },
    { from = "mix.outR", to = "outR" },
  },

  macros = {
    { id = "depth", label = "Depth", unit = "%", min = 0, max = 100, default = 60,
      targets = { { to = "headA.flutterDepth", min = 0.0, max = 0.7 },
                  { to = "headB.flutterDepth", min = 0.0, max = 0.7 } } },
    { id = "rate", label = "Rate", unit = "Hz", min = 0.2, max = 2.0, default = 0.7,
      targets = { { to = "headA.flutterRate", min = 0.2, max = 2.0 },
                  { to = "headB.flutterRate", min = 0.2, max = 2.0 } } },
    { id = "wander", label = "Wander", unit = "%", min = 0, max = 100, default = 50,
      targets = { { to = "headA.wowDepth", min = 0.0, max = 1.0 },
                  { to = "headB.wowDepth", min = 0.0, max = 1.0 },
                  { to = "headA.wowVariance", min = 0.0, max = 0.2 },
                  { to = "headB.wowVariance", min = 0.0, max = 0.2 } } },
    { id = "spread", label = "Spread", unit = "%", min = 0, max = 100, default = 100,
      targets = { { to = "leanA.gainLR", min = 0.0, max = 0.35 },
                  { to = "leanA.gainRR", min = 1.0, max = 0.65 },
                  { to = "leanB.gainRL", min = 0.0, max = 0.35 },
                  { to = "leanB.gainLL", min = 1.0, max = 0.65 } } },
    { id = "tone", label = "Tone", unit = "dB", min = -6, max = 6, default = -2.5,
      targets = { { to = "toneL.tiltDb", min = -6, max = 6 },
                  { to = "toneR.tiltDb", min = -6, max = 6 } } },
    { id = "wet", label = "Wet", unit = "dB", min = -60, max = 0, default = -2,
      targets = { { to = "wet.gainDb", min = -60, max = 0 } } },
  },
}
