-- Family 4: multi-voice ensemble (tri-chorus).
-- Three TapeDelay voices with their own seed, rate, base delay and drift, so their
-- modulation is independent. Each voice runs at 1/sqrt(3), -4.77 dB, so three voices sum to
-- the level of one. Matrices lean the voices left, centre and right. Each macro is one knob; its
-- default is in the knob's own units and reproduces the parameter values below.
return {
  version = 1,
  name = "Ensemble Tri-Chorus",

  io = { inputs = { "inL", "inR" }, outputs = { "outL", "outR" } },

  nodes = {
    { id = "voice1", type = "TapeDelay", config = { baseDelayMs = 11, seed = 101 },
      params = { wowDepth = 0.50, wowRate = 0.30, wowVariance = 0.20, wowDrift = 0.20, flutterDepth = 0.40, flutterRate = 0.60 } },
    { id = "voice2", type = "TapeDelay", config = { baseDelayMs = 15, seed = 202 },
      params = { wowDepth = 0.50, wowRate = 0.40, wowVariance = 0.20, wowDrift = 0.20, flutterDepth = 0.48, flutterRate = 0.80 } },
    { id = "voice3", type = "TapeDelay", config = { baseDelayMs = 20, seed = 303 },
      params = { wowDepth = 0.50, wowRate = 0.50, wowVariance = 0.20, wowDrift = 0.20, flutterDepth = 0.58, flutterRate = 1.05 } },

    { id = "gain1", type = "Gain", params = { gainDb = -4.77 } },
    { id = "gain2", type = "Gain", params = { gainDb = -4.77 } },
    { id = "gain3", type = "Gain", params = { gainDb = -4.77 } },
    { id = "lean1", type = "Matrix", params = { gainLL = 1.0, gainLR = 0.4, gainRL = 0.0, gainRR = 0.6 } },
    { id = "lean2", type = "Matrix", params = { gainLL = 0.8, gainLR = 0.2, gainRL = 0.2, gainRR = 0.8 } },
    { id = "lean3", type = "Matrix", params = { gainLL = 0.6, gainLR = 0.0, gainRL = 0.4, gainRR = 1.0 } },
    { id = "sum12", type = "Mixer" },
    { id = "sum123", type = "Mixer" },

    { id = "toneL", type = "TiltEQ", params = { tiltDb = -2.0, pivotHz = 1000 } },
    { id = "toneR", type = "TiltEQ", params = { tiltDb = -2.0, pivotHz = 1000 } },
    { id = "wet", type = "Gain", params = { gainDb = -2.0 } },
    { id = "dry", type = "Gain", params = { gainDb = 0.0 } },
    { id = "mix", type = "Mixer" },
  },

  edges = {
    { from = "inL", to = "voice1.inL" },
    { from = "inR", to = "voice1.inR" },
    { from = "inL", to = "voice2.inL" },
    { from = "inR", to = "voice2.inR" },
    { from = "inL", to = "voice3.inL" },
    { from = "inR", to = "voice3.inR" },

    { from = "voice1.outL", to = "gain1.inL" },
    { from = "voice1.outR", to = "gain1.inR" },
    { from = "voice2.outL", to = "gain2.inL" },
    { from = "voice2.outR", to = "gain2.inR" },
    { from = "voice3.outL", to = "gain3.inL" },
    { from = "voice3.outR", to = "gain3.inR" },

    { from = "gain1.outL", to = "lean1.inL" },
    { from = "gain1.outR", to = "lean1.inR" },
    { from = "gain2.outL", to = "lean2.inL" },
    { from = "gain2.outR", to = "lean2.inR" },
    { from = "gain3.outL", to = "lean3.inL" },
    { from = "gain3.outR", to = "lean3.inR" },

    { from = "lean1.outL", to = "sum12.in1L" },
    { from = "lean1.outR", to = "sum12.in1R" },
    { from = "lean2.outL", to = "sum12.in2L" },
    { from = "lean2.outR", to = "sum12.in2R" },
    { from = "sum12.outL", to = "sum123.in1L" },
    { from = "sum12.outR", to = "sum123.in1R" },
    { from = "lean3.outL", to = "sum123.in2L" },
    { from = "lean3.outR", to = "sum123.in2R" },

    { from = "sum123.outL", to = "toneL.in" },
    { from = "sum123.outR", to = "toneR.in" },
    { from = "toneL.out", to = "wet.inL" },
    { from = "toneR.out", to = "wet.inR" },
    { from = "wet.outL", to = "mix.in1L" },
    { from = "wet.outR", to = "mix.in1R" },
    { from = "inL", to = "dry.inL" },
    { from = "inR", to = "dry.inR" },
    { from = "dry.outL", to = "mix.in2L" },
    { from = "dry.outR", to = "mix.in2R" },
    { from = "mix.outL", to = "outL" },
    { from = "mix.outR", to = "outR" },
  },

  macros = {
    { id = "depth", label = "Depth", unit = "%", min = 0, max = 100, default = 60,
      targets = { { to = "voice1.flutterDepth", min = 0.0, max = 0.6667 },
                  { to = "voice2.flutterDepth", min = 0.0, max = 0.8 },
                  { to = "voice3.flutterDepth", min = 0.0, max = 0.9667 } } },
    { id = "rate", label = "Rate", unit = "Hz", min = 0.2, max = 2.0, default = 0.8,
      targets = { { to = "voice1.flutterRate", min = 0.15, max = 1.5 },
                  { to = "voice2.flutterRate", min = 0.2, max = 2.0 },
                  { to = "voice3.flutterRate", min = 0.2625, max = 2.625 } } },
    { id = "wander", label = "Wander", unit = "%", min = 0, max = 100, default = 40,
      targets = { { to = "voice1.wowVariance", min = 0.0, max = 0.5 },
                  { to = "voice2.wowVariance", min = 0.0, max = 0.5 },
                  { to = "voice3.wowVariance", min = 0.0, max = 0.5 },
                  { to = "voice1.wowDrift", min = 0.0, max = 0.5 },
                  { to = "voice2.wowDrift", min = 0.0, max = 0.5 },
                  { to = "voice3.wowDrift", min = 0.0, max = 0.5 } } },
    { id = "spread", label = "Spread", unit = "%", min = 0, max = 100, default = 100,
      targets = { { to = "lean1.gainLR", min = 0.0, max = 0.4 },
                  { to = "lean1.gainRR", min = 1.0, max = 0.6 },
                  { to = "lean2.gainLL", min = 1.0, max = 0.8 },
                  { to = "lean2.gainLR", min = 0.0, max = 0.2 },
                  { to = "lean2.gainRL", min = 0.0, max = 0.2 },
                  { to = "lean2.gainRR", min = 1.0, max = 0.8 },
                  { to = "lean3.gainLL", min = 1.0, max = 0.6 },
                  { to = "lean3.gainRL", min = 0.0, max = 0.4 } } },
    { id = "tone", label = "Tone", unit = "dB", min = -6, max = 6, default = -2,
      targets = { { to = "toneL.tiltDb", min = -6, max = 6 },
                  { to = "toneR.tiltDb", min = -6, max = 6 } } },
    { id = "wet", label = "Wet", unit = "dB", min = -60, max = 0, default = -2,
      targets = { { to = "wet.gainDb", min = -60, max = 0 } } },
  },
}
