#!/usr/bin/env python3
"""Generate src/includes/Graph/Presets/ChorusPresets.h from Presets/lua/*.lua.

Each .lua file is one graph preset. A file name like 01_tape_vibrato.lua gives the preset
name "tape_vibrato" (the numeric prefix only orders the files) and the C++ constant
kTapeVibrato. The Lua text is embedded byte for byte in a raw string literal that starts
on the constant's own line, so a line number in the Lua file is the same line number
inside the constant. The output is deterministic, so it can be compared with --check.

Refuses what it cannot embed safely: non-ASCII text, an empty file, a body over the
MSVC string-literal limit, a file name that is not a valid preset name, or two files
that map to the same name.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PRESET_DIR = ROOT / "src" / "includes" / "Graph" / "Presets"
LUA_DIR = PRESET_DIR / "lua"
HEADER = PRESET_DIR / "ChorusPresets.h"

MAX_BODY_BYTES = 16000
STEM_PATTERN = re.compile(r"^(?:\d+_)?([a-z][a-z0-9_]*)$")

HEADER_TEXT = """\
// Generated by dev-scripts/generate_graph_presets.py from Graph/Presets/lua/*.lua.
// Do not edit: change the .lua files and run dev-scripts/dev-generate-presets.sh.
#pragma once

#include <array>
#include <string_view>

namespace AbacDsp::Graph::Presets
{

struct Preset
{
    std::string_view name;
    std::string_view lua;
};

// clang-format off
"""


class PresetError(ValueError):
    """A preset file that cannot be turned into a header constant."""


@dataclass(frozen=True)
class Preset:
    name: str
    constant: str
    lua: str


def constant_name(name: str) -> str:
    return "k" + "".join(part.capitalize() for part in name.split("_") if part)


def read_lua(path: Path) -> str:
    raw = path.read_bytes()
    try:
        text = raw.decode("ascii")
    except UnicodeDecodeError as error:
        raise PresetError(f"{path.name}: non-ASCII byte at offset {error.start}") from error
    text = text.replace("\r\n", "\n")
    if not text.strip():
        raise PresetError(f"{path.name}: file is empty")
    if len(text.encode("ascii")) > MAX_BODY_BYTES:
        raise PresetError(f"{path.name}: {len(text)} bytes exceeds the {MAX_BODY_BYTES} byte limit")
    return text if text.endswith("\n") else text + "\n"


def load_presets(lua_dir: Path) -> list[Preset]:
    presets: list[Preset] = []
    seen: dict[str, str] = {}
    for path in sorted(lua_dir.glob("*.lua")):
        match = STEM_PATTERN.match(path.stem)
        if match is None:
            raise PresetError(f"{path.name}: name must look like [NN_]lower_snake_case.lua")
        name = match.group(1)
        if name in seen:
            raise PresetError(f"{path.name}: same preset name as {seen[name]}")
        seen[name] = path.name
        presets.append(Preset(name, constant_name(name), read_lua(path)))
    return presets


def raw_delimiter(body: str) -> str:
    delimiter = "lua"
    while f"){delimiter}\"" in body:
        delimiter += "x"
    return delimiter


def render_constant(preset: Preset) -> str:
    delimiter = raw_delimiter(preset.lua)
    return (
        f"inline constexpr std::string_view {preset.constant} = "
        f"R\"{delimiter}({preset.lua}){delimiter}\";\n"
    )


def render_header(presets: list[Preset]) -> str:
    parts = [HEADER_TEXT]
    parts.extend(render_constant(preset) + "\n" for preset in presets)
    parts.append(f"inline constexpr std::array<Preset, {len(presets)}> kChorusPresets{{{{\n")
    parts.extend(f"    {{\"{preset.name}\", {preset.constant}}},\n" for preset in presets)
    parts.append("}};\n// clang-format on\n\n}\n")
    return "".join(parts)


def parse_arguments(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if the header is out of date")
    parser.add_argument("--lua-dir", type=Path, default=LUA_DIR)
    parser.add_argument("--output", type=Path, default=HEADER)
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    arguments = parse_arguments(argv)
    try:
        presets = load_presets(arguments.lua_dir)
    except PresetError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2
    if not presets:
        print(f"error: no .lua files in {arguments.lua_dir}", file=sys.stderr)
        return 2

    header = render_header(presets)
    current = arguments.output.read_text(encoding="ascii") if arguments.output.exists() else None
    if arguments.check:
        if current != header:
            print(f"{arguments.output} is out of date: run dev-scripts/dev-generate-presets.sh", file=sys.stderr)
            return 1
        print(f"{arguments.output.name} is up to date ({len(presets)} presets)")
        return 0
    if current != header:
        arguments.output.write_text(header, encoding="ascii")
    print(f"{arguments.output.name}: {len(presets)} presets")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
